hierarchy = ["country", "locality", "organizationalUnit", "inetOrgPerson"]
count     = [ 1       , 2         , 3                   , 4 ]

[locality]
rdn = "l"
l = 'file("cities.txt")'

[country]
rdn = "c"
c='lowercase(file("country-codes.txt"))'

[organizationalUnit]
rdn = "ou"
ou = 'file("regions.txt")'

[inetOrgPerson]
rdn="uid"
uid='lowercase(combine(file("firstname.txt"), ".", file("lastname.txt")))'
givenName='file("firstname.txt")'
sn='file("lastname.txt")'
cn='combine(file("firstname.txt"), " ", file("lastname.txt"))'
